on:
    push:
    
jobs:
    tsc:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                    node-version: 14
            - name: install tsc
              run: npm i typescript -D
            - name: tsc
              run: npx tsc ./pub.worker.ts
              
            - name: Auto committing js files
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                file_pattern: "*.js"
                push_options: '--force'
                commit_message: "github action: tsc - carbee-public"
                branch: minify
    minify:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@master
            - uses: actions/checkout@v2
    
            - name: Auto Minify
              uses: nizarmah/auto-minify@v2.1.1
              with: 
                directory: "./pub.worker.js"
                output: "./pub/min"
                js_engine: uglify-js
        
            - name: Auto committing minified files
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                push_options: '--force'
                commit_message: "github action: auto minify - carbee-public"
                branch: minify
