on:
    push:

jobs:
    minify:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@master
            - uses: actions/checkout@v2
    
            - name: Auto Minify
              uses: nizarmah/auto-minify@v2.1.1
              with: 
                directory: "./pub.worker.js"
                output: "./pub/min"
                js_engine: uglify-js
        
            - name: Auto committing minified files
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: "github action: auto minify - carbee-public"
                branch: ${{github.ref}}
# TODO branch protected
